export const BOOKSHELF_FACTOR = 0.5;
export const BOOKSHELF_ROTATE_MAX = 3;
export const BOOKSHELF_ROTATE_OUTSIDE_VIEW = 0;
export const BOOKSHELF_TRANSPARENCY_OUTSIDE_VIEW = 0;
export const BOOKSHELF_TRANSPARENCY_IN_VIEW = 1;
export const BOOKSHELF_VELOCITY_INITIAL = 0;
export const BOOKSHELF_ANIMATION_DAMPING = 30;
export const BOOKSHELF_ANIMATION_STIFFNESS = 300;
export const BOOKSHELF_COVER_SIZE = 64;

export const THIRTY_FIVE_WEEKS_IN_MS = 35 * 7 * 24 * 60 * 60 * 1000;

export const GOOGLE_ANALYTICS_ID = "G-TKEZZNZ9RP";

export const HEVY_API_URL = "https://api.hevyapp.com/v1";
