name: CI
on:
  push:
    branches:
      - "master"
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false

      - name: Cache node_modules 📦
        uses: actions/cache@v3.4.0
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: public
          target_branch: gh-pages
          fqdn: balajmarius.com
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
