name: CI
on:
  push:
    branches:
      - "master"
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false

      - name: Cache
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          build_dir: public
          target_branch: gh-pages
          fqdn: balajmarius.com
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
